// GENERATED by `drizzle-kit pull` from the live Postgres schema (36 tables).
// Alembic (backend/alembic) is still the migration authority until the Python
// backend is retired, so after a migration re-run:
//   node --env-file=.env.local node_modules/drizzle-kit/bin.cjs pull
// and re-apply the edits below. Hand edits:
//   1. timestamps use mode 'date' (we do date arithmetic in services)
//   2. events.id uses mode 'number' (avoids BigInt in JSON)
//   3. drizzle-kit emits `.default(')` for empty-string defaults; fix to `.default('')`
// NOTE: Python supplies many column defaults (ids, booleans) itself, so the
// database has none. Inserts here must set them explicitly.
import { pgTable, varchar, uniqueIndex, uuid, integer, boolean, index, foreignKey, bigserial, jsonb, timestamp, unique, numeric, smallint, text } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const alembicVersion = pgTable("alembic_version", {
	versionNum: varchar("version_num", { length: 32 }).primaryKey().notNull(),
});

export const plans = pgTable("plans", {
	id: uuid().primaryKey().notNull(),
	code: varchar().notNull(),
	countryCode: varchar("country_code").notNull(),
	currencyCode: varchar("currency_code").notNull(),
	amountMinor: integer("amount_minor").notNull(),
	active: boolean().notNull(),
}, (table) => [
	uniqueIndex("ux_plans_code_country_active").using("btree", table.code.asc().nullsLast().op("text_ops"), table.countryCode.asc().nullsLast().op("text_ops")).where(sql`active`),
]);

export const events = pgTable("events", {
	id: bigserial({ mode: "number" }).primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	sessionId: uuid("session_id"),
	type: varchar().notNull(),
	payload: jsonb(),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_events_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	index("ix_events_outlet_id_occurred_at").using("btree", table.outletId.asc().nullsLast().op("timestamptz_ops"), table.occurredAt.asc().nullsLast().op("uuid_ops")),
	index("ix_events_outlet_id_type_occurred_at").using("btree", table.outletId.asc().nullsLast().op("timestamptz_ops"), table.type.asc().nullsLast().op("uuid_ops"), table.occurredAt.asc().nullsLast().op("uuid_ops")),
	index("ix_events_session_id").using("btree", table.sessionId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "events_outlet_id_fkey"
		}),
]);

export const payments = pgTable("payments", {
	id: uuid().primaryKey().notNull(),
	subscriptionId: uuid("subscription_id").notNull(),
	providerPaymentId: varchar("provider_payment_id"),
	amountMinor: integer("amount_minor").notNull(),
	currencyCode: varchar("currency_code").notNull(),
	status: varchar().notNull(),
	webhookVerified: boolean("webhook_verified").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_payments_subscription_id").using("btree", table.subscriptionId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.subscriptionId],
			foreignColumns: [subscriptions.id],
			name: "payments_subscription_id_fkey"
		}),
	unique("payments_provider_payment_id_key").on(table.providerPaymentId),
]);

export const placeSnapshots = pgTable("place_snapshots", {
	id: bigserial({ mode: "number" }).primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	rating: numeric({ precision: 2, scale:  1 }),
	reviewCount: integer("review_count"),
	polledAt: timestamp("polled_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_place_snapshots_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	index("ix_place_snapshots_outlet_id_polled_at").using("btree", table.outletId.asc().nullsLast().op("timestamptz_ops"), table.polledAt.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "place_snapshots_outlet_id_fkey"
		}),
]);

export const sessions = pgTable("sessions", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	deviceHash: varchar("device_hash"),
	rating: smallint(),
	selectedTagIds: uuid("selected_tag_ids").array(),
	completed: boolean().notNull(),
	countedForTrial: boolean("counted_for_trial").notNull(),
	startedAt: timestamp("started_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	completedAt: timestamp("completed_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	index("ix_sessions_dedup_lookup").using("btree", table.outletId.asc().nullsLast().op("text_ops"), table.deviceHash.asc().nullsLast().op("uuid_ops"), table.startedAt.asc().nullsLast().op("uuid_ops")),
	index("ix_sessions_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	index("ix_sessions_outlet_id_started_at").using("btree", table.outletId.asc().nullsLast().op("uuid_ops"), table.startedAt.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "sessions_outlet_id_fkey"
		}),
]);

export const tags = pgTable("tags", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	label: jsonb().notNull(),
	phrases: jsonb().notNull(),
	sortOrder: integer("sort_order").notNull(),
	active: boolean().notNull(),
}, (table) => [
	index("ix_tags_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	index("ix_tags_outlet_id_sort_order").using("btree", table.outletId.asc().nullsLast().op("int4_ops"), table.sortOrder.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "tags_outlet_id_fkey"
		}),
]);

export const privateFeedback = pgTable("private_feedback", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	sessionId: uuid("session_id").notNull(),
	rating: smallint(),
	message: text().notNull(),
	contact: varchar(),
	resolved: boolean().notNull(),
	resolvedAt: timestamp("resolved_at", { withTimezone: true, mode: 'date' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_private_feedback_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	index("ix_private_feedback_outlet_id_created_at").using("btree", table.outletId.asc().nullsLast().op("timestamptz_ops"), table.createdAt.asc().nullsLast().op("uuid_ops")),
	index("ix_private_feedback_outlet_id_resolved").using("btree", table.outletId.asc().nullsLast().op("uuid_ops"), table.resolved.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "private_feedback_outlet_id_fkey"
		}),
	foreignKey({
			columns: [table.sessionId],
			foreignColumns: [sessions.id],
			name: "private_feedback_session_id_fkey"
		}),
]);

export const otpCodes = pgTable("otp_codes", {
	id: uuid().primaryKey().notNull(),
	accountId: uuid("account_id").notNull(),
	code: varchar({ length: 6 }).notNull(),
	magicToken: varchar("magic_token").notNull(),
	attempts: integer().notNull(),
	consumed: boolean().notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_otp_codes_account_id").using("btree", table.accountId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [accounts.id],
			name: "otp_codes_account_id_fkey"
		}),
	unique("otp_codes_magic_token_key").on(table.magicToken),
]);

export const ownerSessions = pgTable("owner_sessions", {
	id: uuid().primaryKey().notNull(),
	accountId: uuid("account_id").notNull(),
	token: varchar().notNull(),
	revoked: boolean().notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_owner_sessions_account_id").using("btree", table.accountId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [accounts.id],
			name: "owner_sessions_account_id_fkey"
		}),
	unique("owner_sessions_token_key").on(table.token),
]);

export const subscriptions = pgTable("subscriptions", {
	id: uuid().primaryKey().notNull(),
	accountId: uuid("account_id").notNull(),
	plan: varchar().notNull(),
	status: varchar().notNull(),
	razorpaySubscriptionId: varchar("razorpay_subscription_id"),
	mandateStatus: varchar("mandate_status"),
	currentPeriodEnd: timestamp("current_period_end", { withTimezone: true, mode: 'date' }),
	graceUntil: timestamp("grace_until", { withTimezone: true, mode: 'date' }),
	cancelledAt: timestamp("cancelled_at", { withTimezone: true, mode: 'date' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	provider: varchar().default('razorpay').notNull(),
	razorpayOrderId: varchar("razorpay_order_id"),
}, (table) => [
	index("ix_subscriptions_account_id").using("btree", table.accountId.asc().nullsLast().op("uuid_ops")),
	index("ix_subscriptions_razorpay_order_id").using("btree", table.razorpayOrderId.asc().nullsLast().op("text_ops")),
	index("ix_subscriptions_razorpay_subscription_id").using("btree", table.razorpaySubscriptionId.asc().nullsLast().op("text_ops")),
	index("ix_subscriptions_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [accounts.id],
			name: "subscriptions_account_id_fkey"
		}),
]);

export const outlets = pgTable("outlets", {
	id: uuid().primaryKey().notNull(),
	accountId: uuid("account_id").notNull(),
	slug: varchar().notNull(),
	businessName: varchar("business_name").notNull(),
	vertical: varchar().notNull(),
	countryCode: varchar("country_code").notNull(),
	locale: varchar().notNull(),
	timezone: varchar().notNull(),
	logoUrl: varchar("logo_url"),
	googlePlaceId: varchar("google_place_id"),
	googleReviewUrl: varchar("google_review_url"),
	state: varchar().notNull(),
	source: varchar().notNull(),
	submittedAt: timestamp("submitted_at", { withTimezone: true, mode: 'date' }),
	approvedAt: timestamp("approved_at", { withTimezone: true, mode: 'date' }),
	approvedBy: varchar("approved_by"),
	rejectionReason: varchar("rejection_reason"),
	placeVerified: boolean("place_verified").notNull(),
	placement: varchar(),
	placementConfirmed: boolean("placement_confirmed").notNull(),
	activatedAt: timestamp("activated_at", { withTimezone: true, mode: 'date' }),
	trialFlowCount: integer("trial_flow_count").notNull(),
	baselineRating: numeric("baseline_rating", { precision: 2, scale:  1 }),
	baselineReviewCount: integer("baseline_review_count"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	lockedAtFlowCount: integer("locked_at_flow_count"),
	hubMode: varchar("hub_mode").default('direct').notNull(),
}, (table) => [
	index("ix_outlets_account_id").using("btree", table.accountId.asc().nullsLast().op("uuid_ops")),
	index("ix_outlets_state").using("btree", table.state.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [accounts.id],
			name: "outlets_account_id_fkey"
		}),
	unique("outlets_slug_key").on(table.slug),
]);

export const accounts = pgTable("accounts", {
	id: uuid().primaryKey().notNull(),
	ownerPhone: varchar("owner_phone").notNull(),
	ownerEmail: varchar("owner_email").notNull(),
	ownerName: varchar("owner_name"),
	otpChannel: varchar("otp_channel").notNull(),
	currencyCode: varchar("currency_code").notNull(),
	paymentProvider: varchar("payment_provider").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	referralCode: varchar("referral_code"),
	referredByAccountId: uuid("referred_by_account_id"),
}, (table) => [
	uniqueIndex("ix_accounts_referral_code").using("btree", table.referralCode.asc().nullsLast().op("text_ops")),
	unique("accounts_owner_phone_key").on(table.ownerPhone),
	unique("accounts_owner_email_key").on(table.ownerEmail),
]);

export const referralRewards = pgTable("referral_rewards", {
	id: uuid().primaryKey().notNull(),
	referrerAccountId: uuid("referrer_account_id").notNull(),
	referredAccountId: uuid("referred_account_id").notNull(),
	status: varchar().default('pending').notNull(),
	discountPercent: integer("discount_percent").default(70).notNull(),
	earnedAt: timestamp("earned_at", { withTimezone: true, mode: 'date' }),
	appliedAt: timestamp("applied_at", { withTimezone: true, mode: 'date' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_referral_rewards_referrer").using("btree", table.referrerAccountId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.referredAccountId],
			foreignColumns: [accounts.id],
			name: "referral_rewards_referred_account_id_fkey"
		}),
	foreignKey({
			columns: [table.referrerAccountId],
			foreignColumns: [accounts.id],
			name: "referral_rewards_referrer_account_id_fkey"
		}),
	unique("referral_rewards_referred_account_id_key").on(table.referredAccountId),
]);

export const leads = pgTable("leads", {
	id: uuid().primaryKey().notNull(),
	email: varchar().notNull(),
	placeId: varchar("place_id").notNull(),
	businessName: varchar("business_name"),
	source: varchar().default('gap_report').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_leads_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
]);

export const outletModules = pgTable("outlet_modules", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	module: varchar().notNull(),
	enabled: boolean().default(false).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	config: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	available: boolean().default(true).notNull(),
}, (table) => [
	index("ix_outlet_modules_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "outlet_modules_outlet_id_fkey"
		}),
	unique("uq_outlet_modules_outlet_module").on(table.outletId, table.module),
]);

export const outletProfiles = pgTable("outlet_profiles", {
	outletId: uuid("outlet_id").primaryKey().notNull(),
	tagline: varchar({ length: 160 }),
	coverImageUrl: varchar("cover_image_url"),
	addressLine: varchar("address_line", { length: 240 }),
	locality: varchar({ length: 120 }),
	phone: varchar({ length: 32 }),
	hours: jsonb(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "outlet_profiles_outlet_id_fkey"
		}),
]);

export const outletLinks = pgTable("outlet_links", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	kind: varchar({ length: 24 }).notNull(),
	label: varchar({ length: 60 }),
	url: varchar({ length: 500 }).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	enabled: boolean().default(true).notNull(),
}, (table) => [
	index("ix_outlet_links_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "outlet_links_outlet_id_fkey"
		}),
]);

export const menuCategories = pgTable("menu_categories", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	name: varchar({ length: 80 }).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
}, (table) => [
	index("ix_menu_categories_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "menu_categories_outlet_id_fkey"
		}),
]);

export const menuItems = pgTable("menu_items", {
	id: uuid().primaryKey().notNull(),
	categoryId: uuid("category_id").notNull(),
	name: varchar({ length: 120 }).notNull(),
	description: varchar({ length: 400 }),
	amountMinor: integer("amount_minor"),
	currencyCode: varchar("currency_code", { length: 3 }).default('INR').notNull(),
	priceOnRequest: boolean("price_on_request").default(false).notNull(),
	pricePrefix: varchar("price_prefix", { length: 12 }),
	durationMin: integer("duration_min"),
	dietary: varchar().array().default([""]).notNull(),
	photoUrl: varchar("photo_url"),
	available: boolean().default(true).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
}, (table) => [
	index("ix_menu_items_category_id").using("btree", table.categoryId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.categoryId],
			foreignColumns: [menuCategories.id],
			name: "menu_items_category_id_fkey"
		}).onDelete("cascade"),
]);

export const printKitOrders = pgTable("print_kit_orders", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	method: varchar({ length: 16 }).notNull(),
	feeMinor: integer("fee_minor").default(0).notNull(),
	currencyCode: varchar("currency_code", { length: 3 }).default('INR').notNull(),
	address: text(),
	phone: varchar({ length: 32 }),
	status: varchar({ length: 16 }).default('requested').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_print_kit_orders_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "print_kit_orders_outlet_id_fkey"
		}),
]);

export const loyaltyPrograms = pgTable("loyalty_programs", {
	outletId: uuid("outlet_id").primaryKey().notNull(),
	cooldownHours: integer("cooldown_hours").default(12).notNull(),
	terms: text(),
	acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true, mode: 'date' }),
	acknowledgedBy: varchar("acknowledged_by"),
}, (table) => [
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "loyalty_programs_outlet_id_fkey"
		}),
]);

export const loyaltyBadges = pgTable("loyalty_badges", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	name: varchar({ length: 60 }).notNull(),
	icon: varchar({ length: 24 }).default('sparkle').notNull(),
	visitsRequired: integer("visits_required").notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	active: boolean().default(true).notNull(),
}, (table) => [
	index("ix_loyalty_badges_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "loyalty_badges_outlet_id_fkey"
		}),
]);

export const loyaltyRewards = pgTable("loyalty_rewards", {
	id: uuid().primaryKey().notNull(),
	badgeId: uuid("badge_id").notNull(),
	type: varchar({ length: 24 }).notNull(),
	percent: integer(),
	valueMinor: integer("value_minor"),
	currencyCode: varchar("currency_code", { length: 3 }).default('INR').notNull(),
	title: varchar({ length: 120 }).notNull(),
	terms: varchar({ length: 400 }),
	expiresDays: integer("expires_days"),
}, (table) => [
	foreignKey({
			columns: [table.badgeId],
			foreignColumns: [loyaltyBadges.id],
			name: "loyalty_rewards_badge_id_fkey"
		}).onDelete("cascade"),
	unique("loyalty_rewards_badge_id_key").on(table.badgeId),
]);

export const loyaltyLedger = pgTable("loyalty_ledger", {
	id: uuid().primaryKey().notNull(),
	memberId: uuid("member_id").notNull(),
	kind: varchar({ length: 24 }).notNull(),
	refId: uuid("ref_id"),
	staffPinId: uuid("staff_pin_id"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_loyalty_ledger_member_id").using("btree", table.memberId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.memberId],
			foreignColumns: [loyaltyMembers.id],
			name: "loyalty_ledger_member_id_fkey"
		}),
]);

export const loyaltyRewardGrants = pgTable("loyalty_reward_grants", {
	id: uuid().primaryKey().notNull(),
	memberId: uuid("member_id").notNull(),
	rewardId: uuid("reward_id").notNull(),
	redeemCode: varchar("redeem_code", { length: 12 }).notNull(),
	issuedAt: timestamp("issued_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }),
	redeemedAt: timestamp("redeemed_at", { withTimezone: true, mode: 'date' }),
	redeemedByPinId: uuid("redeemed_by_pin_id"),
}, (table) => [
	index("ix_loyalty_grants_member_id").using("btree", table.memberId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.memberId],
			foreignColumns: [loyaltyMembers.id],
			name: "loyalty_reward_grants_member_id_fkey"
		}),
	foreignKey({
			columns: [table.rewardId],
			foreignColumns: [loyaltyRewards.id],
			name: "loyalty_reward_grants_reward_id_fkey"
		}),
	unique("loyalty_reward_grants_redeem_code_key").on(table.redeemCode),
]);

export const staffPins = pgTable("staff_pins", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	label: varchar({ length: 60 }).notNull(),
	pinHash: varchar("pin_hash", { length: 128 }).notNull(),
	active: boolean().default(true).notNull(),
	failedAttempts: integer("failed_attempts").default(0).notNull(),
	lockedUntil: timestamp("locked_until", { withTimezone: true, mode: 'date' }),
}, (table) => [
	index("ix_staff_pins_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "staff_pins_outlet_id_fkey"
		}),
]);

export const serviceCatalog = pgTable("service_catalog", {
	id: uuid().primaryKey().notNull(),
	key: varchar({ length: 40 }).notNull(),
	name: varchar({ length: 80 }).notNull(),
	tagline: varchar({ length: 160 }).notNull(),
	descriptionMd: text("description_md").default('').notNull(),
	deliverables: jsonb().default([]).notNull(),
	questions: jsonb().default([]).notNull(),
	leadTimeDays: integer("lead_time_days"),
	coverImageUrl: varchar("cover_image_url"),
	active: boolean().default(true).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
}, (table) => [
	unique("service_catalog_key_key").on(table.key),
]);

export const serviceRequestEvents = pgTable("service_request_events", {
	id: uuid().primaryKey().notNull(),
	requestId: uuid("request_id").notNull(),
	kind: varchar({ length: 20 }).notNull(),
	body: text().notNull(),
	actor: varchar({ length: 8 }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_service_request_events_request_id").using("btree", table.requestId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.requestId],
			foreignColumns: [serviceRequests.id],
			name: "service_request_events_request_id_fkey"
		}).onDelete("cascade"),
]);

export const competitorWatches = pgTable("competitor_watches", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	placeId: varchar("place_id").notNull(),
	name: varchar().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_competitor_watches_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "competitor_watches_outlet_id_fkey"
		}),
	unique("uq_competitor_watch_outlet_place").on(table.outletId, table.placeId),
]);

export const competitorSnapshots = pgTable("competitor_snapshots", {
	id: bigserial({ mode: "number" }).primaryKey().notNull(),
	watchId: uuid("watch_id").notNull(),
	rating: numeric({ precision: 2, scale:  1 }),
	reviewCount: integer("review_count"),
	polledAt: timestamp("polled_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_competitor_snapshots_watch_polled").using("btree", table.watchId.asc().nullsLast().op("timestamptz_ops"), table.polledAt.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.watchId],
			foreignColumns: [competitorWatches.id],
			name: "competitor_snapshots_watch_id_fkey"
		}).onDelete("cascade"),
]);

export const notifications = pgTable("notifications", {
	id: uuid().primaryKey().notNull(),
	accountId: uuid("account_id").notNull(),
	outletId: uuid("outlet_id"),
	template: varchar().notNull(),
	channel: varchar().notNull(),
	status: varchar().notNull(),
	error: varchar(),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'date' }),
	toPhone: varchar("to_phone"),
	body: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("ix_notifications_account_id").using("btree", table.accountId.asc().nullsLast().op("uuid_ops")),
	index("ix_notifications_account_id_sent_at").using("btree", table.accountId.asc().nullsLast().op("timestamptz_ops"), table.sentAt.asc().nullsLast().op("uuid_ops")),
	index("ix_notifications_outlet_id_template").using("btree", table.outletId.asc().nullsLast().op("uuid_ops"), table.template.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [accounts.id],
			name: "notifications_account_id_fkey"
		}),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "notifications_outlet_id_fkey"
		}),
]);

export const serviceRequests = pgTable("service_requests", {
	id: uuid().primaryKey().notNull(),
	accountId: uuid("account_id").notNull(),
	outletId: uuid("outlet_id").notNull(),
	serviceId: uuid("service_id").notNull(),
	status: varchar({ length: 16 }).default('requested').notNull(),
	brief: text(),
	answers: jsonb(),
	quotedAmountMinor: integer("quoted_amount_minor"),
	currencyCode: varchar("currency_code", { length: 3 }).default('INR').notNull(),
	dueAt: timestamp("due_at", { withTimezone: true, mode: 'date' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	paidAt: timestamp("paid_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	index("ix_service_requests_account_id").using("btree", table.accountId.asc().nullsLast().op("uuid_ops")),
	index("ix_service_requests_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	index("ix_service_requests_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [accounts.id],
			name: "service_requests_account_id_fkey"
		}),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "service_requests_outlet_id_fkey"
		}),
	foreignKey({
			columns: [table.serviceId],
			foreignColumns: [serviceCatalog.id],
			name: "service_requests_service_id_fkey"
		}),
]);

export const loyaltyMembers = pgTable("loyalty_members", {
	id: uuid().primaryKey().notNull(),
	outletId: uuid("outlet_id").notNull(),
	publicId: varchar("public_id", { length: 8 }).notNull(),
	name: varchar({ length: 80 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	deviceTokenHash: varchar("device_token_hash", { length: 64 }).notNull(),
	codeSecret: varchar("code_secret", { length: 64 }).notNull(),
	contactConsent: boolean("contact_consent").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'date' }),
	transferHash: varchar("transfer_hash", { length: 64 }),
	transferExpiresAt: timestamp("transfer_expires_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	index("ix_loyalty_members_device").using("btree", table.deviceTokenHash.asc().nullsLast().op("text_ops")),
	index("ix_loyalty_members_outlet_id").using("btree", table.outletId.asc().nullsLast().op("uuid_ops")),
	index("ix_loyalty_members_public_id").using("btree", table.publicId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.outletId],
			foreignColumns: [outlets.id],
			name: "loyalty_members_outlet_id_fkey"
		}),
	unique("uq_loyalty_member_phone").on(table.outletId, table.phone),
]);

export const servicePayments = pgTable("service_payments", {
	id: uuid().primaryKey().notNull(),
	accountId: uuid("account_id").notNull(),
	kind: varchar({ length: 20 }).notNull(),
	refId: uuid("ref_id").notNull(),
	amountMinor: integer("amount_minor").notNull(),
	currencyCode: varchar("currency_code", { length: 3 }).default('INR').notNull(),
	provider: varchar({ length: 16 }).notNull(),
	providerOrderId: varchar("provider_order_id").notNull(),
	providerPaymentId: varchar("provider_payment_id"),
	status: varchar({ length: 12 }).default('created').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	paidAt: timestamp("paid_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	index("ix_service_payments_account_id").using("btree", table.accountId.asc().nullsLast().op("uuid_ops")),
	index("ix_service_payments_ref_id").using("btree", table.refId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [accounts.id],
			name: "service_payments_account_id_fkey"
		}),
	unique("service_payments_provider_order_id_key").on(table.providerOrderId),
]);
