"""add otp and owner session tables

Revision ID: 255eebb1473d
Revises: 8f278cf12ca3
Create Date: 2026-09-25 03:42:16.178968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '255eebb1473d'
down_revision: Union[str, None] = '8f278cf12ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('magic_token', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('magic_token')
    )
    op.create_index(op.f('ix_otp_codes_account_id'), 'otp_codes', ['account_id'], unique=False)
    op.create_table('owner_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_owner_sessions_account_id'), 'owner_sessions', ['account_id'], unique=False)
    # NOTE: autogenerate also proposed dropping several composite/partial
    # indexes (events, notifications, place_snapshots, plans, private_feedback,
    # sessions, tags) because they were added by hand in the initial migration
    # rather than declared on the SQLAlchemy model metadata. Those are
    # deliberate (documents/05-DATA-MODEL.md) and must NOT be dropped —
    # removed here rather than left for a future accidental apply.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_sessions_account_id'), table_name='owner_sessions')
    op.drop_table('owner_sessions')
    op.drop_index(op.f('ix_otp_codes_account_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
