"""initial schema

Revision ID: 8f278cf12ca3
Revises: 
Create Date: 2026-09-25 00:51:29.456997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8f278cf12ca3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_phone', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('otp_channel', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_email'),
    sa.UniqueConstraint('owner_phone')
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.Column('google_review_url', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('place_verified', sa.Boolean(), nullable=False),
    sa.Column('placement', sa.String(), nullable=True),
    sa.Column('placement_confirmed', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_flow_count', sa.Integer(), nullable=False),
    sa.Column('baseline_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('baseline_review_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_outlets_account_id'), 'outlets', ['account_id'], unique=False)
    op.create_index(op.f('ix_outlets_state'), 'outlets', ['state'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(), nullable=True),
    sa.Column('mandate_status', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_account_id'), 'subscriptions', ['account_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_outlet_id'), 'events', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=True),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_account_id'), 'notifications', ['account_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('webhook_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('place_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('polled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_snapshots_outlet_id'), 'place_snapshots', ['outlet_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('device_hash', sa.String(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('selected_tag_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('counted_for_trial', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_outlet_id'), 'sessions', ['outlet_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('label', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_outlet_id'), 'tags', ['outlet_id'], unique=False)
    op.create_table('private_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_feedback_outlet_id'), 'private_feedback', ['outlet_id'], unique=False)
    # ### end Alembic commands ###

    # --- Additional indexes per documents/05-DATA-MODEL.md (not inferrable from
    # single-column `index=True`) ---

    # tags(outlet_id, sort_order) — ordered chip vocabulary lookup (§3.3)
    op.create_index('ix_tags_outlet_id_sort_order', 'tags', ['outlet_id', 'sort_order'])

    # sessions(outlet_id, started_at) and dedup lookup (§3.4)
    op.create_index('ix_sessions_outlet_id_started_at', 'sessions', ['outlet_id', 'started_at'])
    op.create_index(
        'ix_sessions_dedup_lookup', 'sessions', ['outlet_id', 'device_hash', 'started_at']
    )

    # events(outlet_id, occurred_at) and (outlet_id, type, occurred_at) — funnel queries (§3.5)
    op.create_index('ix_events_outlet_id_occurred_at', 'events', ['outlet_id', 'occurred_at'])
    op.create_index(
        'ix_events_outlet_id_type_occurred_at', 'events', ['outlet_id', 'type', 'occurred_at']
    )

    # private_feedback(outlet_id, created_at desc) and (outlet_id, resolved) — inbox views (§3.6)
    op.create_index(
        'ix_private_feedback_outlet_id_created_at',
        'private_feedback',
        ['outlet_id', sa.text('created_at DESC')],
    )
    op.create_index(
        'ix_private_feedback_outlet_id_resolved', 'private_feedback', ['outlet_id', 'resolved']
    )

    # place_snapshots(outlet_id, polled_at desc) — before/after view (§3.7)
    op.create_index(
        'ix_place_snapshots_outlet_id_polled_at',
        'place_snapshots',
        ['outlet_id', sa.text('polled_at DESC')],
    )

    # notifications(account_id, sent_at desc) and (outlet_id, template) — dup-send guard (§3.10)
    op.create_index(
        'ix_notifications_account_id_sent_at',
        'notifications',
        ['account_id', sa.text('sent_at DESC')],
    )
    op.create_index('ix_notifications_outlet_id_template', 'notifications', ['outlet_id', 'template'])

    # plans: unique (code, country_code) where active — one active price per market (§3.9a)
    op.create_index(
        'ux_plans_code_country_active',
        'plans',
        ['code', 'country_code'],
        unique=True,
        postgresql_where=sa.text('active'),
    )


def downgrade() -> None:
    # --- Drop additional indexes first (reverse of upgrade) ---
    op.drop_index('ux_plans_code_country_active', table_name='plans')
    op.drop_index('ix_notifications_outlet_id_template', table_name='notifications')
    op.drop_index('ix_notifications_account_id_sent_at', table_name='notifications')
    op.drop_index('ix_place_snapshots_outlet_id_polled_at', table_name='place_snapshots')
    op.drop_index('ix_private_feedback_outlet_id_resolved', table_name='private_feedback')
    op.drop_index('ix_private_feedback_outlet_id_created_at', table_name='private_feedback')
    op.drop_index('ix_events_outlet_id_type_occurred_at', table_name='events')
    op.drop_index('ix_events_outlet_id_occurred_at', table_name='events')
    op.drop_index('ix_sessions_dedup_lookup', table_name='sessions')
    op.drop_index('ix_sessions_outlet_id_started_at', table_name='sessions')
    op.drop_index('ix_tags_outlet_id_sort_order', table_name='tags')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_private_feedback_outlet_id'), table_name='private_feedback')
    op.drop_table('private_feedback')
    op.drop_index(op.f('ix_tags_outlet_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sessions_outlet_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_place_snapshots_outlet_id'), table_name='place_snapshots')
    op.drop_table('place_snapshots')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_account_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_outlet_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_account_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_outlets_state'), table_name='outlets')
    op.drop_index(op.f('ix_outlets_account_id'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_table('plans')
    op.drop_table('accounts')
    # ### end Alembic commands ###
