"""simplify desc indexes to ascending

Postgres serves ORDER BY x DESC efficiently from a plain ascending index by
scanning backward, so these three DESC indexes (added by hand in the initial
migration) are simplified to match what the SQLAlchemy model metadata now
declares — closing the last gap between hand-authored migration state and
model-declared state (see notes in 255eebb1473d and a1352953cc0e).

Revision ID: 9c5c7251639c
Revises: a1352953cc0e
Create Date: 2026-09-25 03:58:49.810116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c5c7251639c'
down_revision: Union[str, None] = 'a1352953cc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_account_id_sent_at'), table_name='notifications')
    op.create_index('ix_notifications_account_id_sent_at', 'notifications', ['account_id', 'sent_at'], unique=False)
    op.drop_index(op.f('ix_place_snapshots_outlet_id_polled_at'), table_name='place_snapshots')
    op.create_index('ix_place_snapshots_outlet_id_polled_at', 'place_snapshots', ['outlet_id', 'polled_at'], unique=False)
    op.drop_index(op.f('ix_private_feedback_outlet_id_created_at'), table_name='private_feedback')
    op.create_index('ix_private_feedback_outlet_id_created_at', 'private_feedback', ['outlet_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_private_feedback_outlet_id_created_at', table_name='private_feedback')
    op.create_index(op.f('ix_private_feedback_outlet_id_created_at'), 'private_feedback', ['outlet_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('ix_place_snapshots_outlet_id_polled_at', table_name='place_snapshots')
    op.create_index(op.f('ix_place_snapshots_outlet_id_polled_at'), 'place_snapshots', ['outlet_id', sa.literal_column('polled_at DESC')], unique=False)
    op.drop_index('ix_notifications_account_id_sent_at', table_name='notifications')
    op.create_index(op.f('ix_notifications_account_id_sent_at'), 'notifications', ['account_id', sa.literal_column('sent_at DESC')], unique=False)
    # ### end Alembic commands ###
